# Generated by Django 5.2.1 on 2025-09-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='reddit',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
