# Generated by Django 5.2.1 on 2025-09-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='socials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
