# Generated by Django 5.2.1 on 2025-09-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0003_studio_alter_anime_studio'),
        ('shared', '0002_franchise_socials'),
        ('yomu', '0002_publisher_alter_work_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
