# Generated by Django 5.2.1 on 2025-10-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_voiceactor_alter_character_played_by_delete_talent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceactor',
            name='website',
        ),
        migrations.AddField(
            model_name='voiceactor',
            name='socials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
