# Generated by Django 5.2.1 on 2025-07-17 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(choices=[(0, 'Winter'), (1, 'Summer'), (2, 'Spring'), (3, 'Fall')], default=0)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('title_ja', models.CharField(blank=True, default='', max_length=500)),
                ('title_romaji', models.CharField(blank=True, default='', max_length=500)),
                ('title_alternatives', models.JSONField(blank=True, default=list)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(blank=True, default='A description will be written later', max_length=1500)),
                ('status', models.IntegerField(choices=[(0, 'Airing'), (1, 'Completed'), (2, 'Upcoming')], default=2)),
                ('type', models.IntegerField(choices=[(0, 'TV'), (1, 'Movie'), (2, 'OVA'), (3, 'ONA'), (4, 'Special')], default=0)),
                ('airing_from', models.DateField(blank=True, null=True)),
                ('airing_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prequels', models.ManyToManyField(blank=True, related_name='sequels', to='miru.anime')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miru.season')),
            ],
            options={
                'verbose_name_plural': 'anime',
                'ordering': ['-airing_from'],
            },
        ),
    ]
