# Generated by Django 5.2.1 on 2025-07-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(blank=True, choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], null=True)),
                ('year', models.IntegerField(blank=True, default=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ja', models.CharField(blank=True, max_length=255, null=True)),
                ('title_romaji', models.CharField(blank=True, max_length=255, null=True)),
                ('title_alternatives', models.JSONField(blank=True, default=list)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(blank=True, default='A synopsis will be written later')),
                ('status', models.IntegerField(choices=[(0, 'Not yet aired'), (1, 'Airing'), (2, 'Finished airing')], default=0)),
                ('type', models.IntegerField(choices=[(0, 'Tv'), (1, 'Movie'), (2, 'OVA'), (3, 'ONA'), (4, 'Web')], default=0)),
                ('score', models.FloatField(blank=True, default=0.0)),
                ('users', models.IntegerField(blank=True, default=0)),
                ('airing_start_date', models.DateField(blank=True, null=True)),
                ('airing_end_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.company')),
                ('genres', models.ManyToManyField(blank=True, related_name='animes', to='shared.genre')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(blank=True, choices=[(0, 'Main'), (1, 'Supporting')], default=1)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miru.anime')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.character')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='animes', through='miru.AnimeCharacter', to='shared.character'),
        ),
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miru.season'),
        ),
    ]
