# Generated by Django 5.2.1 on 2025-09-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-year']},
        ),
    ]
