# Generated by Django 5.2.1 on 2025-07-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='company',
            new_name='studio',
        ),
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 'All ages'), (1, 'Children'), (2, 'Teens 13 or older'), (3, '17+ (Violence/Profanity)')], default=0),
        ),
    ]
