# Generated by Django 5.2.1 on 2025-07-24 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0002_rename_company_anime_studio_anime_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True, choices=[('prequel', 'Prequel'), ('sequel', 'Sequel'), ('spinoff', 'Spin-off'), ('side_story', 'Side Story'), ('alternataive_version', 'Alternate'), ('other', 'Other')], default='other')),
                ('from_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='miru.anime')),
                ('to_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='miru.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='related_anime', through='miru.AnimeRelation', to='miru.anime'),
        ),
    ]
