# Generated by Django 5.1.1 on 2024-11-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0003_character_alter_anime_genres_anime_characters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='visual',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
