# Generated by Django 5.2.1 on 2025-08-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0003_animerelation_anime_related'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['-score']},
        ),
    ]
