# Generated by Django 5.2.1 on 2025-11-05 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiku', '0002_remove_artist_website_artist_socials_and_more'),
        ('miru', '0003_studio_alter_anime_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_episode', models.SmallIntegerField(blank=True, null=True)),
                ('ending_episode', models.SmallIntegerField(blank=True, null=True)),
                ('theme_type', models.IntegerField(blank=True, choices=[(0, 'Opening'), (1, 'Ending')], default=0)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='miru.anime')),
                ('kiku_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiku.album')),
            ],
            options={
                'ordering': ['theme_type', 'starting_episode'],
            },
        ),
    ]
