# Generated by Django 5.2.1 on 2025-08-17 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0004_alter_anime_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='slug',
        ),
        migrations.AddField(
            model_name='anime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='summary',
            field=models.TextField(default='A synopsis will be written later'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='users',
            field=models.IntegerField(default=0),
        ),
    ]
