# Generated by Django 5.1.1 on 2024-11-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0004_anime_visual'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='visual',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='characters/'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='visual',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='anime/'),
        ),
    ]
