# Generated by Django 5.1.1 on 2024-11-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0005_character_visual_alter_anime_visual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='character_animes', to='miru.character'),
        ),
    ]
