# Generated by Django 5.2.1 on 2025-08-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0005_remove_anime_slug_anime_created_at_anime_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
