# Generated by Django 5.1.1 on 2024-11-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0006_alter_anime_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='score_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='users',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
