# Generated by Django 5.1.1 on 2024-11-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0007_anime_score_anime_score_breakdown_anime_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='next_anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_in_series', to='miru.anime'),
        ),
        migrations.AddField(
            model_name='anime',
            name='previous_anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_in_series', to='miru.anime'),
        ),
    ]
