# Generated by Django 5.1.1 on 2024-11-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0008_anime_next_anime_anime_previous_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.CharField(choices=[('g', 'G (General Audience)'), ('pg', 'PG (Parental Guidence)'), ('pg-13', 'PG-13 (Teens 13 and Up)'), ('r', 'R (Restricted 17+)'), ('r+', 'R (Explicit 18+)')], default='g', max_length=40),
        ),
        migrations.AddField(
            model_name='anime',
            name='source',
            field=models.CharField(choices=[('manga', 'Manga'), ('light', 'Light Novel'), ('vn', 'Visual Novel'), ('mnwha', 'Manwha'), ('game', 'Video Game'), ('original', 'Original'), ('other', 'Other')], default='original', max_length=50),
        ),
    ]
