# Generated by Django 5.1.1 on 2024-11-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0009_anime_rating_anime_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='licenors',
            field=models.ManyToManyField(blank=True, related_name='licensor_animes', to='miru.licensor'),
        ),
        migrations.AddField(
            model_name='anime',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='producer_animes', to='miru.producer'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(blank=True, related_name='studio_animes', to='miru.studio'),
        ),
    ]
