# Generated by Django 5.2.1 on 2025-08-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('users', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(default='A synopsis will be written later.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_alternatives', models.JSONField(blank=True, default=list)),
                ('status', models.IntegerField(choices=[(0, 'Not Publishing'), (1, 'Publishing'), (2, 'Completed')], default=0)),
                ('total_volumes', models.IntegerField(blank=True, null=True)),
                ('total_chapters', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('manga', 'Manga'), ('light_novel', 'Light Novel (LN)'), ('novel', 'Novel'), ('manwha', 'Manwha (KR)'), ('manhua', 'Manhua (CN)'), ('doujinshi', 'Doujinshi'), ('web_novel', 'Web Novel')], default='manga')),
                ('publishing_start_date', models.DateField(blank=True, null=True)),
                ('publishing_end_date', models.DateField(blank=True, null=True)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.franchise')),
                ('genres', models.ManyToManyField(blank=True, related_name='works', to='shared.genre')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.company')),
            ],
            options={
                'ordering': ['-score'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(blank=True, choices=[(0, 'Writer'), (1, 'Artist'), (2, 'Writer & Artist')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yomu.author')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yomu.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='works', through='yomu.WorkAuthor', to='yomu.author'),
        ),
        migrations.CreateModel(
            name='WorkCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(blank=True, choices=[(0, 'Main'), (1, 'Supporting')], default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yomu.work')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.AddField(
            model_name='work',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='works', through='yomu.WorkCharacter', to='characters.character'),
        ),
        migrations.CreateModel(
            name='WorkRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True, choices=[('prequel', 'Prequel'), ('sequel', 'Sequel'), ('spinoff', 'Spin-off'), ('side_story', 'Side Story'), ('alternative_version', 'Alternate'), ('other', 'Other')], default='other')),
                ('from_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_works', to='yomu.work')),
                ('to_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_works', to='yomu.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='related_works', through='yomu.WorkRelation', to='yomu.work'),
        ),
    ]
