import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/pages/home.css"
import SideNav from "./components/navigation/sideNav";
import TopNav from "./components/navigation/topNav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="content">
          <SideNav />
          <main className="main">
            <TopNav />
            <div className="page">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
