import type { Metadata } from "next";
import "../static/css/main.css"
import TopNav from "./components/navigation/topNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <div className="content">
          <main className="main">
            <TopNav />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
