# Generated by Django 5.2.1 on 2025-08-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chipset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GPUMemoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Microarchitecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.IntegerField(blank=True, choices=[(0, 'Other'), (1, 'Black'), (2, 'White'), (3, 'Red'), (4, 'Blue'), (5, 'Yellow'), (6, 'Green')], null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('core_clock', models.IntegerField(help_text='MHz')),
                ('boost_clock', models.IntegerField(help_text='MHz')),
                ('vram', models.IntegerField()),
                ('memory_clock', models.IntegerField(blank=True, help_text='MHz', null=True)),
                ('memory_bus', models.IntegerField(blank=True, help_text='bits', null=True)),
                ('length', models.IntegerField(blank=True, help_text='mm', null=True)),
                ('tdp', models.IntegerField(blank=True, help_text='Watts', null=True)),
                ('suggested_psu', models.IntegerField(blank=True, help_text='Watts', null=True)),
                ('slot_width', models.IntegerField(choices=[(1, 'Single-slot'), (2, 'Dual-slot'), (3, 'Triple-slot'), (4, 'Quadruple-slot')], default=2)),
                ('memory_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kumitateru.gpumemorytype')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kumitateru.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.IntegerField(blank=True, choices=[(0, 'Other'), (1, 'Black'), (2, 'White'), (3, 'Red'), (4, 'Blue'), (5, 'Yellow'), (6, 'Green')], null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('modules', models.IntegerField(default=1, help_text='Number of sticks/modules')),
                ('speed', models.IntegerField(blank=True, help_text='MT/s', null=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kumitateru.manufacturer')),
                ('memory_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kumitateru.memorytype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.IntegerField(blank=True, choices=[(0, 'Other'), (1, 'Black'), (2, 'White'), (3, 'Red'), (4, 'Blue'), (5, 'Yellow'), (6, 'Green')], null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('form_factor', models.IntegerField(choices=[(0, 'Mini-ITX'), (1, 'Micro-ATX'), (2, 'ATX'), (3, 'eATX')], default=2)),
                ('memory_slots', models.IntegerField()),
                ('max_memory', models.IntegerField()),
                ('m2_slots', models.IntegerField()),
                ('sata_slots', models.IntegerField()),
                ('chipset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kumitateru.chipset')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kumitateru.manufacturer')),
                ('memory_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kumitateru.memorytype')),
                ('socket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kumitateru.socket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.IntegerField(blank=True, choices=[(0, 'Other'), (1, 'Black'), (2, 'White'), (3, 'Red'), (4, 'Blue'), (5, 'Yellow'), (6, 'Green')], null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('core_count', models.IntegerField()),
                ('thread_count', models.IntegerField()),
                ('core_clock', models.FloatField(help_text='GHz')),
                ('boost_clock', models.FloatField(help_text='GHz')),
                ('l2_cache', models.IntegerField(blank=True, help_text='MB', null=True)),
                ('l3_cache', models.IntegerField(blank=True, help_text='MB', null=True)),
                ('tdp', models.IntegerField(help_text='Watts')),
                ('max_temp', models.IntegerField(blank=True, help_text='Celcius', null=True)),
                ('is_unlocked', models.BooleanField(help_text='Overclockable')),
                ('has_graphics', models.BooleanField()),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kumitateru.manufacturer')),
                ('microarchitecture', models.ForeignKey(blank=True, help_text='Codename', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kumitateru.microarchitecture')),
                ('socket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kumitateru.socket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
