# Generated by Django 5.2.1 on 2025-09-01 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('users', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(default='A synopsis will be written later.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('announced', 'Announced'), ('early_access', 'Early Access'), ('released', 'Released'), ('end_of_service', 'End of Service')], default='announced')),
                ('esrb_rating', models.CharField(blank=True, choices=[('early_childhood', 'Early Childhood'), ('everyone', 'Everyone'), ('everyone_10', 'Everyone 10+'), ('teen', 'Teen'), ('mature', 'Mature'), ('pending', 'Rating Pending')], default='everyone', null=True)),
                ('pegi_rating', models.IntegerField(blank=True, choices=[(3, 'PEGI 3'), (7, 'PEGI 7'), (12, 'PEGI 12'), (16, 'PEGI 16'), (18, 'PEGI 18')], default=3, null=True)),
                ('has_campaign_mode', models.BooleanField(default=False)),
                ('has_pvp_mode', models.BooleanField(default=False)),
                ('has_pve_mode', models.BooleanField(default=False)),
                ('is_on_console', models.BooleanField(default=False)),
                ('is_on_pc', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('developers', models.ManyToManyField(blank=True, related_name='developed_games', to='asobu.company')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.franchise')),
                ('genres', models.ManyToManyField(blank=True, related_name='tagged_games', to='shared.genre')),
                ('publishers', models.ManyToManyField(blank=True, related_name='published_games', to='asobu.company')),
            ],
            options={
                'ordering': ['-score'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asobu.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(blank=True, choices=[(0, 'Main'), (1, 'Supporting')], default=1)),
                ('is_playable', models.BooleanField(blank=True, default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asobu.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='appears_in_games', through='asobu.GameCharacter', to='characters.character'),
        ),
        migrations.CreateModel(
            name='GameRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True, choices=[('prequel', 'Prequel'), ('sequel', 'Sequel'), ('spinoff', 'Spin-off'), ('side_story', 'Side Story'), ('alternative_version', 'Alternate'), ('other', 'Other')], default='other')),
                ('from_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_games', to='asobu.game')),
                ('to_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_games', to='asobu.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='related_games', through='asobu.GameRelation', to='asobu.game'),
        ),
        migrations.AddConstraint(
            model_name='gamerelation',
            constraint=models.UniqueConstraint(fields=('from_game', 'to_game', 'relation_type'), name='unique_game_relation'),
        ),
    ]
