# Generated by Django 5.2.1 on 2025-09-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asobu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerelation',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('series_entry', 'Series Entry'), ('spinoff', 'Spin-off'), ('side_story', 'Side Story'), ('alternative_version', 'Alternate'), ('other', 'Other')], default='other'),
        ),
    ]
