# Generated by Django 5.2.1 on 2025-10-06 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_voiceactor_alter_character_played_by_delete_talent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bio', models.TextField(blank=True, default='A bio will be written at a later date.')),
                ('website', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('character', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profile', to='characters.character')),
                ('voice_actor_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profile', to='characters.voiceactor')),
            ],
            options={
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Single'), (1, 'Standard'), (2, 'Live Album'), (3, 'Extended Play'), (4, 'Soundtrack'), (5, 'Compilation')], default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('artists', models.ManyToManyField(related_name='albums', to='kiku.artist')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiku.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('plays', models.IntegerField(blank=0, default=0)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='kiku.album')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_songs', to='kiku.artist')),
                ('genre', models.ManyToManyField(blank=True, related_name='songs', to='kiku.genre')),
            ],
        ),
    ]
