# Generated by Django 5.2.1 on 2025-10-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='website',
        ),
        migrations.AddField(
            model_name='artist',
            name='socials',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='special_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
